name: Code check

on: pull_request

jobs:
  check:
    name: Check project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.pnpm-store
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-accordion-${{ hashFiles('**/pnpm-lock.yaml') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-accordion-

      - name: Install dependencies
        run: pnpm install

      - name: Run TypeScript check
        run: pnpm run ts:check

      - name: Run ESLint check
        run: pnpm run lint:check

      - name: Run Prettier check
        run: pnpm run format:check

  tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            ~/.pnpm-store
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-accordion-${{ hashFiles('**/pnpm-lock.yaml') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-accordion-

      - name: Install dependencies
        run: pnpm install

      - name: Run unit tests
        run: pnpm run test
